import Head from "next/head";
import { GetServerSideProps } from "next";

import Dashboard from "./dashboard";

export const getServerSideProps: GetServerSideProps = async () => {
  try {
    const api = "http://localhost:3333";
    const result = await fetch(`${api}/products`, { cache: 'no-cache' });
    const { data } = await result.json();
    const { products } = data;
    products.forEach((product: any) => {
      product.image = `${api}/images/${product.image}`;
      product.formattedPrice = new Intl.NumberFormat("pt-BR", {
        style: "currency",
        currency: "BRL",
      }).format(product.price);
      product.splitPrice = new Intl.NumberFormat("pt-BR", {
        style: "currency",
        currency: "BRL",
      }).format(product.price / 10);
    });
    return {
      props: {
        productsApi: products,
      },
    };
  } catch (error: any) {
    console.error(error.message)
    return {
      props: {
        productsApi: [],
      },
    };
  }
};

export default function Home({ productsApi }: any) {
  return (
    <>
      <Head>
        <title>Imagineshop - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Dashboard productList={productsApi} />
    </>
  );
}
